export const ExchangePaymentConfig: {
    title_buy: string;
    title_sell: string;
    subTitle_buy: string;
    subTitle_sell: string;
    img: string;
    type: TPaymentMethod;
    more: string;
}[] = [
    {
        title_buy: 'Pay by card',
        title_sell: 'Sell by card',
        subTitle_buy: 'Waiting for payment 1 minute',
        subTitle_sell: 'Waiting for withdrawal up to 24 hours',
        img: '/img/payment/card.svg',
        type: 'card',
        more: '+30',
    },
    {
        title_buy: 'Pay crypto',
        title_sell: 'Sell by crypto',
        subTitle_buy: 'Waiting for payment 5 minutes',
        subTitle_sell: 'Waiting for withdrawal up to 24 hours',
        type: 'crypto',
        img: '/img/payment/crypto.svg',
        more: '+20',
    },
];

export type TPaymentMethod = 'card' | 'crypto';

export const CURRENCY_LIST = [
    { name: 'usd', value: 'usd' },
    { name: 'eur', value: 'eur' },
    { name: 'gbp', value: 'gbp' },
    { name: 'sgd', value: 'sgd' },
    { name: 'chf', value: 'chf' },
    { name: 'sek', value: 'sek' },
    { name: 'cad', value: 'cad' },
    { name: 'aud', value: 'aud' },
    { name: 'nok', value: 'nok' },
    { name: 'pln', value: 'pln' },
    { name: 'nzd', value: 'nzd' },
    { name: 'ils', value: 'ils' },
    { name: 'dkk', value: 'dkk' },
    { name: 'czk', value: 'czk' },
    { name: 'brl', value: 'brl' },
    { name: 'aed', value: 'aed' },
    { name: 'mxn', value: 'mxn' },
    { name: 'zar', value: 'zar' },
    { name: 'huf', value: 'huf' },
    { name: 'php', value: 'php' },
    { name: 'try', value: 'try' },
    { name: 'bgn', value: 'bgn' },
    { name: 'ron', value: 'ron' },
    { name: 'amd', value: 'amd' },
    { name: 'uyu', value: 'uyu' },
    { name: 'inr', value: 'inr' },
    { name: 'thb', value: 'thb' },
    { name: 'vnd', value: 'vnd' },
    { name: 'lkr', value: 'lkr' },
    { name: 'cop', value: 'cop' },
    { name: 'kzt', value: 'kzt' },
    { name: 'pen', value: 'pen' },
    { name: 'qar', value: 'qar' },
    { name: 'jod', value: 'jod' },
    { name: 'hkd', value: 'hkd' },
    { name: 'twd', value: 'twd' },
    { name: 'ghs', value: 'ghs' },
    { name: 'dop', value: 'dop' },
    // { name: 'jmd', value: 'jmd' },
    // { name: 'jod', value: 'jod' },
    // { name: 'jpy', value: 'jpy' },
    // { name: 'kes', value: 'kes' },
    // { name: 'kgs', value: 'kgs' },
    // { name: 'khr', value: 'khr' },
    // { name: 'krw', value: 'krw' },
    // { name: 'kwd', value: 'kwd' },
    // { name: 'kyd', value: 'kyd' },
    // { name: 'kzt', value: 'kzt' },
    // { name: 'lkr', value: 'lkr' },
    // { name: 'mad', value: 'mad' },
    // { name: 'mdl', value: 'mdl' },
    // { name: 'mkd', value: 'mkd' },
    // { name: 'mop', value: 'mop' },
    // { name: 'mur', value: 'mur' },
    // { name: 'mxn', value: 'mxn' },
    // { name: 'myr', value: 'myr' },
    // { name: 'mzn', value: 'mzn' },
    // { name: 'nad', value: 'nad' },
    // { name: 'ngn', value: 'ngn' },
    // { name: 'nok', value: 'nok' },
    // { name: 'nzd', value: 'nzd' },
    // { name: 'omr', value: 'omr' },
    // { name: 'pab', value: 'pab' },
    // { name: 'pen', value: 'pen' },
    // { name: 'pgk', value: 'pgk' },
    // { name: 'php', value: 'php' },
    // { name: 'pln', value: 'pln' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
    // { name: 'myr', value: 'myr' },
];
